CREATE DATABASE TURBO_AZ
USE TURBO_AZ

CREATE TABLE MARKA (
Id INT PRIMARY KEY IDENTITY(1,1),
 [Name] nvarchar(255) NOT NULL,
);

CREATE TABLE MODEL (
ID INT PRIMARY KEY IDENTITY,
 [NAME] NVARCHAR(25) NOT NULL,
 MARKAID INT FOREIGN KEY REFERENCES MARKA(ID)
);

CREATE TABLE RENG (
ID INT PRIMARY KEY IDENTITY,
 [NAME] NVARCHAR(25) NOT NULL
);
CREATE TABLE IL (
ID INT PRIMARY KEY IDENTITY,
 [NAME] NVARCHAR(25) NOT NULL
);
CREATE TABLE MUHERRIK_HECMI (
ID INT PRIMARY KEY IDENTITY,
 [NAME] NVARCHAR(25) NOT NULL
);
CREATE TABLE BAZAR (
ID INT PRIMARY KEY IDENTITY,
 [NAME] NVARCHAR(25) NOT NULL
);
CREATE TABLE BAN_NOVU (
ID INT PRIMARY KEY IDENTITY,
 [NAME] NVARCHAR(25) NOT NULL
);

CREATE TABLE YANACAQ_NOVU (
ID INT PRIMARY KEY IDENTITY,
 [NAME] NVARCHAR(25) NOT NULL
);

CREATE TABLE SURETLER_QUTUSU (
ID INT PRIMARY KEY IDENTITY,
 [NAME] NVARCHAR(25) NOT NULL
);

CREATE TABLE SEHERLER (
ID INT PRIMARY KEY IDENTITY(1,1),
 [NAME] nvarchar(25) NOT NULL,
);

CREATE TABLE ELAQE (
ID INT PRIMARY KEY IDENTITY,
 [NAME] NVARCHAR(255) NOT NULL,
 EMAIL NVARCHAR(255) NOT NULL,
 PHONE NVARCHAR(255) NOT NULL,
 SEHERID INT FOREIGN KEY REFERENCES SEHERLER(ID)
);

CREATE TABLE TECHIZAT (
ID INT PRIMARY KEY IDENTITY(1,1),
 [NAME] NVARCHAR(25) NOT NULL,
);

CREATE TABLE ELAN (
 ID INT PRIMARY KEY IDENTITY,
 MODELID INT FOREIGN KEY REFERENCES MODEL(ID),
 BANID INT FOREIGN KEY REFERENCES BAN_NOVU(ID),
 YURUS INT NOT NULL,
 YURUS_VAHIDI INT NOT NULL,
 RENGID INT FOREIGN KEY REFERENCES RENG(ID),
 QIYMET INT NOT NULL,
 VALYUTA INT NOT NULL,
 SAHIB_SAYI INT NOT NULL,
 YANACAQID INT FOREIGN KEY REFERENCES YANACAQ_NOVU(ID),
 OTURUCU INT NOT NULL,
 SURETLER_QUTUSU_ID INT FOREIGN KEY REFERENCES SURETLER_QUTUSU(ID),
 ILID INT FOREIGN KEY REFERENCES IL(ID),
 MUHERRIK_HECMI_ID INT FOREIGN KEY REFERENCES MUHERRIK_HECMI(ID),
 BAZARID INT FOREIGN KEY REFERENCES BAZAR(ID),
 VURUGU TINYINT ,
 RENGLENIB TINYINT ,
 QEZALIDIR TINYINT ,
 YERLERIN_SAYI INT NOT NULL,
 KREDIT TINYINT ,
 BARTER TINYINT ,
 WINKOD NVARCHAR(255) NOT NULL,
 ELAVE_MELUMAT NVARCHAR(255) NOT NULL,
 ELAQEID INT FOREIGN KEY REFERENCES ELAQE(ID),
 MUHERRIK_GUCU INT NOT NULL,
);

CREATE TABLE IMAGES (
ID INT PRIMARY KEY IDENTITY,
 [NAME] NVARCHAR(255) NOT NULL,
 ELANID INT FOREIGN KEY REFERENCES ELAN(ID)
);

CREATE TABLE ELANTECHIZAT (
ID INT PRIMARY KEY IDENTITY,
 ELANID INT FOREIGN KEY REFERENCES ELAN(ID),
 TECHIZATID INT FOREIGN KEY REFERENCES TECHIZAT(ID)
);

INSERT INTO BAN_NOVU 
VALUES 
('AVTOBUS'),
('SEDAN'),
('MINIVAN'),
('UNIVERSAL'),
('OFFROADER')

INSERT INTO BAZAR 
VALUES 
('AMERIKA'),
('AVROPA'),
('DUBAY'),
('KOREA'),
('YAPONIYA')

INSERT INTO IL 
VALUES 
('2024'),
('2023'),
('2022'),
('2021'),
('2020')

INSERT INTO MARKA 
VALUES 
('BMW'),
('MERCEDES'),
('KIA'),
('HYUNDAI'),
('JEEP')

INSERT INTO MODEL 
VALUES 
('F30',1),
('X5',1),
('E-CLASS',2),
('C-CLASS',2),
('OPTIMA',3),
('SORENTO',3),
('SANTAFE',4),
('ELANTRA',4),
('WRANGLER',5)

INSERT INTO MUHERRIK_HECMI 
VALUES 
('2200'),
('2100'),
('2000'),
('1900'),
('1800'),
('1700'),
('1600'),
('1500'),
('1400')

INSERT INTO RENG 
VALUES 
('AG'),
('QARA'),
('BOZ'),
('METALIK'),
('GOY'),
('QIRMIZI'),
('BORDO'),
('SARI'),
('YASIL')


INSERT INTO SEHERLER 
VALUES 
('BAKI'),
('QEBELE'),
('GENCE'),
('SUMQAYIT'),
('MINGECEVIR'),
('AGDAM'),
('LACIN'),
('XOCALI'),
('SUSA')

INSERT INTO SURETLER_QUTUSU 
VALUES 
('AVTOMAT'),
('MEXANIKA'),
('ROBOT')

INSERT INTO TECHIZAT 
VALUES 
('YUNGUL LEHIMLI DISKLER'),
('ABS'),
('LYUK'),
('PARK RADARI'),
('KSENON'),
('DERI SALON'),
('KONDISIONER')

INSERT INTO YANACAQ_NOVU 
VALUES 
('BENZIN'),
('DIZEL'),
('QAZ')

INSERT INTO ELAQE 
VALUES 
('NADIR','NADIR@GMAIL.COM','0555111552',1),
('USER1','USER1@GMAIL.COM','0505551155',2),
('USER2','USER2@GMAIL.COM','0777177777',3),
('USER3','USER3@GMAIL.COM','0995991199',4),
('USER4','USER4@GMAIL.COM','0105110011',5)


INSERT INTO ELAN 
VALUES 
('1','2',155200,1,1,15500,1,3,1,1,1,1,2,1,0,1,1,5,0,0,'WAEDAWAWD15451','IDEAL VEZIYYETDEDIR',1,275),
('2','1',106000,1,2,25300,1,2,2,2,2,2,3,2,1,0,1,7,0,0,'WAEGH45WD15214','ORTA VEZIYYETDEDIR',2,175),
('1','2',115400,1,3,35500,1,1,3,1,1,3,4,3,0,1,1,5,0,0,'WAEDA454WD152G','NORMAL VEZIYYETDEDIR',3,190),
('1','2',185400,1,4,28800,1,2,1,1,2,4,5,4,1,0,1,5,0,0,'W257AWAWDGH851','MASIN ASIB',4,230),
('1','2',55600,1,5,14200,1,3,2,1,1,5,1,1,0,1,1,7,0,0,'W257AWAW3T4451','TEKERLERI TEZEDIR',5,164)


INSERT INTO ELANTECHIZAT 
VALUES 
(1,1),
(1,4),
(1,5),
(1,6),
(2,1),
(2,2),
(2,3),
(2,5),
(2,6),
(3,2),
(3,3),
(3,4),
(3,5),
(4,1),
(4,2),
(4,4),
(5,1),
(5,5),
(5,6)

INSERT INTO IMAGES 
VALUES 
('IMAGE1',1),
('IMAGE2',1),
('IMAGE3',1),
('IMAGE4',2),
('IMAGE5',2),
('IMAGE6',3),
('IMAGE7',3),
('IMAGE8',4),
('IMAGE9',4),
('IMAGE10',5),
('IMAGE11',5),
('IMAGE124',5)

SELECT e.ID,ma.[Name] MARKA,m.[NAME] MODEL,b.[NAME] BAN_NOVU,r.[NAME] RENGI,Y.[NAME] YANACAQ_NOVU,s.[NAME] Suretler_qutusu,
i.[NAME] ILI,MH.[NAME] MUHERRIK_HECMI,BA.[NAME] BURAXILDIGI_BAZAR,e.YURUS,e.QIYMET, e.SAHIB_SAYI SS, e.YERLERIN_SAYI YS, 
e.WINKOD, e.ELAVE_MELUMAT,e.MUHERRIK_GUCU,EL.[NAME] SATICININ_ADI,EL.EMAIL EMAIL,EL.PHONE TELEFON_NOMRESI,SH.[NAME],T.[NAME] TECHIZAT FROM ELAN e
JOIN MODEL m
ON
e.MODELID=m.ID
JOIN MARKA ma
ON
m.MARKAID=ma.Id
JOIN BAN_NOVU b
ON
e.BANID=b.ID
JOIN RENG r
ON
e.RENGID=r.ID
JOIN YANACAQ_NOVU Y
ON
e.YANACAQID=Y.ID
JOIN SURETLER_QUTUSU s
ON
e.SURETLER_QUTUSU_ID=s.ID
JOIN IL i
ON
e.ILID=i.ID
JOIN MUHERRIK_HECMI MH
ON
e.MUHERRIK_HECMI_ID=MH.ID
JOIN BAZAR BA
ON
e.BAZARID=BA.ID
JOIN ELAQE EL
ON
e.ELAQEID=EL.ID
JOIN SEHERLER SH
ON
EL.SEHERID=SH.ID
JOIN ELANTECHIZAT ET
ON
ET.ELANID=E.ID
JOIN TECHIZAT T
ON 
ET.TECHIZATID=T.ID